#!/usr/bin/env zsh

source ~/.zshrc

cd ~/"Projects&Competitions"/CS108_Project/Maze/
mkdir -p GameData

touch GameData/path.txt

if [ ! -f "GameData/LeastTimes.txt" ]; then
  {
    echo 15
    echo 40
    echo 120
  } >> "GameData/LeastTimes.txt"
fi

python game.py > /dev/null
